spring:
  cloud:
    gateway:
      routes:

        # ---- CLIENT SERVICE (PORT 8088) ----
        - id: r1
          uri: http://localhost:8088
          predicates:
            - Path=/clients/**

        - id: r2
          uri: http://localhost:8088
          predicates:
            - Path=/client/*

        # ---- VOITURE SERVICE (PORT 8089) ----
        - id: r3
          uri: http://localhost:8089
          predicates:
            - Path=/voitures/**
